version: "3.7"
services:
  nginx:
    image: "nginx:latest"
    container_name: next-page-nginx
    restart: unless-stopped
    volumes:
      - /home/ec2-user/KDT-STUDY2-3/deploy/kdt1-study-2-team1-front/conf:/etc/nginx/conf.d
      - /home/ec2-user/KDT-STUDY2-3/deploy/kdt1-study-2-team1-front/html:/usr/share/nginx/html
    ports:
      - "8080"
    networks:
      - app

networks:
  app:
    name: server_network
    external: true